### ISSUE TITLE
question for  gto_fastq_mutate

### ISSUE THREAD

**Issue by hmyh1202** [cobilab/gto2#7]
Hi.
  
   I used gto_fastq_mutate for simulate fastq data  but the fastq file of outfile only change the sequence but not the quality of the sequence, so the length of quality and base is not match.

The Best！

**Comment by pratas** [comment]
Hi,

It is supposed not to change.
Here the idea is only to simulate a SNP in the sequence (independently from the quality-score).
Nevertheless, this a good idea to implement in future applications. Thank you!

Best regards,
Diogo
